"""check-paths: Sync schema <-> wiki docs <-> target repo symlinks."""

import os
import shutil
import subprocess
import sys
from pathlib import Path

from .lib import (
    AGENT_INDEX_FILENAME, CONFLICT_LOG, DOCS_ROOT, NEW_ENTRY_LOG, TEMPLATE_FILE, WIKI_ROOT,
    add_to_schema, append_log, clear_conflict_log_for, clear_flag, doc_path,
    get_config_flag, get_doc_filename, get_repo_path, git_head_hash,
    load_conflict_log, load_schema, now_ts,
    save_schema, schema_paths, set_flag, symlink_path, untracked_paths,
    walk_schema, write_metadata_footer,
)

_WIKI_BANNER = (
    "> **WIKI MANAGED** — This file is a symlink; edits here edit the wiki directly.\n"
    "> Check `.agent-wiki/flags.json` before any doc work.\n"
    "> Update guidance: `.agent-wiki/agents/WIKI_UPDATE.md` · "
    "Conflict guidance: `.agent-wiki/agents/WIKI_MERGE.md` · "
    "House rules: `.agent-wiki/instructions.md` · "
    "Index: `.agent-wiki/AGENT-INDEX.md`\n\n"
    "---\n\n"
)


def ensure_root_banner(quiet: bool = False):
    fn = get_doc_filename()
    root_doc = DOCS_ROOT / fn
    if not root_doc.exists():
        return
    content = root_doc.read_text()
    if "**WIKI MANAGED**" in content:
        return
    root_doc.write_text(_WIKI_BANNER + content)
    if not quiet:
        print(f"  [create-banner]  docs/{fn}")


def ensure_wiki_doc(rel_path: str, source: str = "manual", quiet: bool = False) -> Path:
    dp = doc_path(rel_path)
    if not dp.exists():
        dp.parent.mkdir(parents=True, exist_ok=True)
        if TEMPLATE_FILE.exists():
            body = TEMPLATE_FILE.read_text().replace("{path}", rel_path or "root")
        else:
            from importlib.resources import files as _pkg_files
            body = _pkg_files("wiki").joinpath("templates/AGENT.template.md").read_text(
                encoding="utf-8"
            ).replace("{path}", rel_path or "root")
        dp.write_text(_WIKI_BANNER + body)
        fn = get_doc_filename()
        display = f"docs/{rel_path}/{fn}" if rel_path else f"docs/{fn}"
        if not quiet:
            print(f"  [created]  {display}")
        repo = get_repo_path()
        write_metadata_footer(dp, rel_path, "agent-wiki check-paths",
                              source_commit=git_head_hash(repo))
        if rel_path:
            append_log(NEW_ENTRY_LOG, {
                "ts": now_ts(),
                "rel_path": rel_path,
                "doc": display,
                "source": source,
            })
            set_flag("new_entry")
    return dp


def make_symlink(link: Path, target: Path, quiet: bool = False):
    link.parent.mkdir(parents=True, exist_ok=True)
    rel = os.path.relpath(target, link.parent)
    link.symlink_to(rel)
    if not quiet:
        print(f"  [symlink]  {link.relative_to(link.parent.parent.parent)} -> {rel}")


def skip_worktree(repo: Path, rel_file: str):
    subprocess.run(
        ["git", "-C", str(repo), "update-index", "--skip-worktree", rel_file],
        capture_output=True,
    )


def absorb_real_file(target_file: Path, wiki_doc: Path, quiet: bool = False):
    wiki_doc.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy(target_file, wiki_doc)
    target_file.unlink()
    make_symlink(target_file, wiki_doc, quiet=quiet)
    if not quiet:
        print(f"  [absorbed] {target_file}")


def _generate_agent_index(schema: dict, repo: Path, nodes: list, quiet: bool = False):
    """Write .agent-wiki/AGENT-INDEX.md — navigation hub for non-hierarchy tools."""
    from .lib import load_config
    repo_name = load_config().get("repo_name", repo.name)
    fn = get_doc_filename()

    def _tree_lines(node: dict, prefix: str = "", indent: int = 0) -> list[str]:
        lines = []
        for raw_key, children in node.items():
            seg = raw_key.rstrip("+~")
            if raw_key.endswith("~"):
                continue
            if seg == "root":
                path = ""
            else:
                path = f"{prefix}/{seg}" if prefix else seg
            pad = "  " * indent
            if raw_key.endswith("+"):
                flat = _mirror_flat_name(path)
                label = "Root" if path == "" else seg
                lines.append(f"{pad}- [{label}](symlinks/{flat})")
            if isinstance(children, dict) and children:
                lines.extend(_tree_lines(children, path, indent + (1 if raw_key.endswith("+") else 0)))
        return lines

    tree = "\n".join(_tree_lines(schema))

    content = (
        f"# Agent Index — {repo_name}\n\n"
        f"> Auto-generated by `agent-wiki push`. Do not edit — re-run push to regenerate.\n\n"
        f"## Documentation Tree\n\n"
        f"{tree}\n\n"
        f"## Agent Resources\n\n"
        f"- [Wiki Reference](agents/llm.md)\n"
        f"- [Update Guide](agents/WIKI_UPDATE.md)\n"
        f"- [Merge Guide](agents/WIKI_MERGE.md)\n\n"
        f"## Status\n\n"
        f"Check `flags.json` before starting doc work.\n"
    )

    index_path = repo / ".agent-wiki" / AGENT_INDEX_FILENAME
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(content)
    if not quiet:
        print(f"  [index]    .agent-wiki/{AGENT_INDEX_FILENAME}")


def _mirror_flat_name(rel_path: str) -> str:
    """Flat symlink name for a doc path: '' → 'root.md', 'frontend/components' → 'frontend-components.md'."""
    ext = Path(get_doc_filename()).suffix or ".md"
    return ("root" if not rel_path else rel_path.replace("/", "-")) + ext


def _create_mirror_symlinks(nodes: list, repo: Path, quiet: bool = False):
    """Rebuild .agent-wiki/symlinks/ as a flat directory of named doc symlinks."""
    symlinks_dir = repo / ".agent-wiki" / "symlinks"

    # Wipe and recreate so stale entries never accumulate
    if symlinks_dir.exists():
        shutil.rmtree(symlinks_dir)
    symlinks_dir.mkdir(parents=True)

    for rel_path, _ in nodes:
        wiki_doc = doc_path(rel_path)
        if not wiki_doc.exists():
            continue
        name = _mirror_flat_name(rel_path)
        mirror = symlinks_dir / name
        rel = os.path.relpath(wiki_doc, symlinks_dir)
        mirror.symlink_to(rel)
        if not quiet:
            print(f"  [mirror]   .agent-wiki/symlinks/{name} -> {rel}")


def run_push_docs(detect_target_docs: bool = False, verify: bool = False, quiet: bool = False) -> dict:
    schema = load_schema()
    repo = get_repo_path()
    nodes = walk_schema(schema)

    if verify:
        _verify_symlinks(nodes, repo)
        return {}

    if not quiet:
        print(f"Checking paths against schema ({len(nodes)} nodes)...")

    new_docs = 0
    symlinks = 0

    # Generate AGENT-INDEX.md first (root symlink will point to it)
    _generate_agent_index(schema, repo, nodes, quiet=quiet)

    for rel_path, _ in nodes:
        was_new = rel_path and not doc_path(rel_path).exists()
        wiki_doc = ensure_wiki_doc(rel_path, quiet=quiet)
        if was_new:
            new_docs += 1

        link = symlink_path(repo, rel_path)

        if rel_path == "":
            # Root symlink points to AGENT-INDEX.md, not directly to the wiki doc
            index_path = repo / ".agent-wiki" / AGENT_INDEX_FILENAME
            if link.is_symlink():
                link.unlink()
            if not link.exists():
                rel = os.path.relpath(index_path, repo)
                link.symlink_to(rel)
                symlinks += 1
                if not quiet:
                    print(f"  [symlink]  {get_doc_filename()} -> {rel}")
        elif link.is_symlink():
            pass
        elif link.exists():
            absorb_real_file(link, wiki_doc, quiet=quiet)
            write_metadata_footer(wiki_doc, rel_path, "agent-wiki push",
                                  source_commit=git_head_hash(repo))
            symlinks += 1
        else:
            make_symlink(link, wiki_doc, quiet=quiet)
            symlinks += 1

        if get_config_flag("skip_worktree", default=True):
            skip_worktree(repo, str(link.relative_to(repo)))

    _create_mirror_symlinks(nodes, repo, quiet=quiet)
    _handle_untracked(schema, repo, quiet=quiet)

    if detect_target_docs:
        _detect_and_integrate(schema, repo, nodes, quiet=quiet)

    clear_flag("docs_out_of_sync")
    if not quiet:
        print("\nDone.")

    return {"symlinks": symlinks, "new_docs": new_docs}


def _verify_symlinks(nodes: list, repo: Path):
    print("Verifying symlinks...")
    broken = []      # symlink gone but wiki doc exists — link needs restoring
    untracked = []   # neither symlink nor wiki doc — schema entry never pushed

    for rel_path, _ in nodes:
        link = symlink_path(repo, rel_path)
        wiki_doc = doc_path(rel_path)

        if not link.exists() and not link.is_symlink():
            if wiki_doc.exists():
                print(f"  [missing]  {link}")
                broken.append(rel_path)
                make_symlink(link, wiki_doc)
            else:
                print(f"  [untracked] {link}")
                untracked.append(rel_path)
                ensure_wiki_doc(rel_path)
                make_symlink(link, wiki_doc)
        elif link.is_symlink() and not link.resolve().exists():
            print(f"  [dead]     {link}")
            broken.append(rel_path)
            link.unlink()
            ensure_wiki_doc(rel_path)
            make_symlink(link, wiki_doc)

    if not broken and not untracked:
        print("  All symlinks OK.")
        clear_flag("docs_out_of_sync")
        return

    flag_value = {}
    if broken:
        flag_value["broken"] = broken
    if untracked:
        flag_value["untracked"] = untracked
    set_flag("docs_out_of_sync", flag_value)

    if broken:
        print(
            f"\n  WARNING: {len(broken)} symlink(s) were missing or dead and have been restored.\n"
            f"  Placeholder docs may need content — run: agent-wiki status",
            file=sys.stderr,
        )
    if untracked:
        print(
            f"\n  WARNING: {len(untracked)} schema entry(s) have never been pushed to the wiki:\n"
            + "".join(f"    {p or '(root)'}\n" for p in untracked)
            + f"  Run: agent-wiki push",
            file=sys.stderr,
        )


def _strip_wiki_metadata(content: str) -> str:
    """Remove the wiki-managed banner and metadata footer from doc content."""
    if content.startswith(_WIKI_BANNER):
        content = content[len(_WIKI_BANNER):]
    marker = "<!-- agent-wiki-meta"
    start = content.rfind(marker)
    if start != -1:
        end = content.find("-->", start)
        if end != -1:
            content = content[:start].rstrip() + "\n"
    return content


def _handle_untracked(schema: dict, repo: Path, quiet: bool = False):
    paths = untracked_paths(schema)
    if not paths:
        return
    fn = get_doc_filename()
    aw_dir = repo / ".agent-wiki"
    for rel_path in paths:
        wiki_doc = doc_path(rel_path)
        link = symlink_path(repo, rel_path)
        if link.is_symlink():
            link.unlink()
            if not quiet:
                print(f"  [untracked] removed symlink {link.relative_to(repo)}")
        if wiki_doc.exists():
            link.parent.mkdir(parents=True, exist_ok=True)
            clean = _strip_wiki_metadata(wiki_doc.read_text())
            link.write_text(clean)
            wiki_doc.unlink()
            if not quiet:
                print(f"  [untracked] moved wiki doc → {link.relative_to(repo)}")
        # Remove the flat mirror symlink from .agent-wiki/symlinks/
        mirror = aw_dir / "symlinks" / _mirror_flat_name(rel_path)
        if mirror.is_symlink():
            mirror.unlink()
            if not quiet:
                print(f"  [untracked] removed mirror .agent-wiki/symlinks/{mirror.name}")


def run_pull_docs(quiet: bool = False, strategy: str = "skip") -> tuple[int, list[str]]:
    """Scan the target repo for unmanaged doc files and absorb them into the wiki.

    strategy: "skip" (default) — flag conflicts and leave both files untouched
              "wiki"           — keep wiki version; replace repo file with symlink
              "repo"           — overwrite wiki with repo version; replace repo file with symlink
    """
    schema = load_schema()
    repo = get_repo_path()
    nodes = walk_schema(schema)
    return _detect_and_integrate(schema, repo, nodes, quiet=quiet, strategy=strategy)


def _detect_and_integrate(
    schema: dict, repo: Path, existing_nodes: list,
    quiet: bool = False, strategy: str = "skip",
) -> tuple[int, list[str]]:
    fn = get_doc_filename()
    if not quiet:
        print(f"\nScanning target repo for unmanaged {fn} files...")
    managed = {
        str(symlink_path(repo, rel).relative_to(repo))
        for rel, _ in existing_nodes
        if symlink_path(repo, rel).is_symlink()
    }
    skipped = set(untracked_paths(schema))
    existing_conflicts = {e["rel_path"] for e in load_conflict_log()}
    found = 0
    conflicts = 0
    absorbed_paths: list[str] = []

    for doc_file in sorted(repo.rglob(fn)):
        if ".git" in doc_file.parts:
            continue
        if doc_file.is_symlink():
            continue
        rel_file = str(doc_file.relative_to(repo))
        if rel_file in managed:
            continue

        rel_path = str(doc_file.parent.relative_to(repo))
        if rel_path == ".":
            rel_path = ""

        if rel_path in skipped:
            continue

        wiki_doc = doc_path(rel_path)

        if wiki_doc.exists():
            if strategy == "skip":
                if rel_path not in existing_conflicts:
                    append_log(CONFLICT_LOG, {
                        "ts": now_ts(),
                        "rel_path": rel_path,
                        "repo_file": str(doc_file),
                        "wiki_doc": str(wiki_doc),
                    })
                    set_flag("multiple_versions")
                if not quiet:
                    label = rel_path or "(root)"
                    print(f"  [conflict] {label} — both wiki and repo versions exist; run `pull --strategy wiki` or `pull --strategy repo` to resolve")
                conflicts += 1
                continue
            elif strategy == "wiki":
                doc_file.unlink()
                make_symlink(doc_file, wiki_doc, quiet=quiet)
                if not quiet:
                    print(f"  [wiki-wins] {doc_file.relative_to(repo)}")
                if rel_path in existing_conflicts:
                    clear_conflict_log_for([rel_path])
                    if not load_conflict_log():
                        clear_flag("multiple_versions")
                absorbed_paths.append(rel_path or "(root)")
                found += 1
                continue
            # strategy == "repo": fall through to absorb_real_file (overwrites wiki)
            if rel_path in existing_conflicts:
                clear_conflict_log_for([rel_path])
                if not load_conflict_log():
                    clear_flag("multiple_versions")

        absorb_real_file(doc_file, wiki_doc, quiet=quiet)
        write_metadata_footer(wiki_doc, rel_path, "agent-wiki pull",
                              source_commit=git_head_hash(repo))
        add_to_schema(schema, rel_path)
        absorbed_paths.append(rel_path or "(root)")
        found += 1
        if not rel_path:
            ensure_root_banner(quiet=quiet)

    if found > 0:
        save_schema(schema)
        if not quiet:
            print(f"\n  Integrated {found} file(s) and updated schema.yaml.")
    if conflicts == 0 and found == 0 and not quiet:
        print(f"  No unmanaged {fn} files found.")
    if conflicts > 0 and not quiet:
        print(f"\n  {conflicts} conflict(s) flagged. Run `agent-wiki pull --strategy wiki` or `--strategy repo` to resolve.")

    return found, absorbed_paths
