use anyhow::{bail, Result};
use std::fs;
use std::path::{Path, PathBuf};

use crate::{
    config::{self, Config},
    git,
    root::{find_git_root, WikiCtx},
    schema,
};

pub struct InitArgs {
    pub doc_filename: String,
    pub no_detect_target_docs: bool,
    pub no_hooks: bool,
    pub wiki_remote: Option<String>,
}

/// Entry point for `agent-wiki init` — discovers the git root from CWD.
pub fn run(args: InitArgs) -> Result<()> {
    let repo_root = find_git_root()?;
    run_in(repo_root, args)?;
    Ok(())
}

/// Initialise `.agent-wiki/` inside `repo_root`. Callable directly from tests.
pub fn run_in(repo_root: PathBuf, args: InitArgs) -> Result<WikiCtx> {
    if !repo_root.join(".git").exists() {
        bail!("Not a git repository: {}", repo_root.display());
    }

    let wiki_root = repo_root.join(".agent-wiki");
    fs::create_dir_all(&wiki_root)?;

    // Nested git repo for the wiki
    if !wiki_root.join(".git").exists() {
        if !git::init(&wiki_root) {
            bail!("git init failed for {}", wiki_root.display());
        }
        println!("  [git init]  .agent-wiki/");
    } else {
        println!("  [exists]    .agent-wiki/.git/  (skipped)");
    }

    // Optional remote
    if let Some(remote) = &args.wiki_remote {
        git::add_remote(&wiki_root, remote);
        println!("  [remote]    origin → {remote}");
    }

    // config.json
    let cfg = Config {
        doc_filename: args.doc_filename.clone(),
    };
    if !wiki_root.join("config.json").exists() {
        config::save(&wiki_root, &cfg)?;
        println!("  [created]   .agent-wiki/config.json");
    } else {
        println!("  [exists]    .agent-wiki/config.json  (skipped)");
    }

    // schema.yaml
    if !wiki_root.join("schema.yaml").exists() {
        schema::save(&wiki_root, &schema::new_default(), &args.doc_filename)?;
        println!("  [created]   .agent-wiki/schema.yaml");
    } else {
        println!("  [exists]    .agent-wiki/schema.yaml  (skipped)");
    }

    // .gitignore inside .agent-wiki/ (gitignores regenerated dirs)
    ensure_wiki_gitignore(&wiki_root)?;

    // Template files
    ensure_templates(&wiki_root)?;

    // logs/flags.json placeholder
    let flags_path = wiki_root.join("logs").join("flags.json");
    if !flags_path.exists() {
        fs::create_dir_all(flags_path.parent().unwrap())?;
        fs::write(&flags_path, "{}\n")?;
        println!("  [created]   .agent-wiki/logs/flags.json");
    }

    // Add .agent-wiki to target repo's .gitignore
    ensure_gitignore(&repo_root)?;

    let ctx = WikiCtx::new(wiki_root);

    // Absorb existing docs
    if !args.no_detect_target_docs {
        let (found, _) = crate::commands::pull::run_detect_and_integrate(&ctx, "repo", true)?;
        if found > 0 {
            println!("  absorbed:   {found} existing doc(s) integrated");
        }
    }

    // Push: create docs + symlinks
    let counts = crate::commands::push::run(&ctx, false)?;

    // agents/ dir: always present, not tied to hook installation
    crate::commands::hook_setup::setup_agents_dir(&ctx)?;
    if counts.symlinks > 0 {
        println!("  symlinks:   {} created", counts.symlinks);
    }
    if counts.new_docs > 0 {
        println!("  new docs:   {} placeholder(s)", counts.new_docs);
    }

    // Git hooks
    if !args.no_hooks {
        crate::commands::hook_setup::run(&ctx, true, true)?;
    }

    println!("\nDone. Wiki is at .agent-wiki/ (its own git repo).");
    if let Some(remote) = &args.wiki_remote {
        println!("  Push docs:  cd .agent-wiki && git add -A && git commit && git push");
        println!("  Recover:    git clone {remote} .agent-wiki/ && agent-wiki push --verify");
    } else {
        println!("  Tip: add a remote to .agent-wiki/ for backup and recovery.");
    }

    Ok(ctx)
}

fn ensure_wiki_gitignore(wiki_root: &Path) -> Result<()> {
    let path = wiki_root.join(".gitignore");
    if path.exists() {
        return Ok(());
    }
    fs::write(
        &path,
        "# Regenerated by agent-wiki — do not commit\nlogs/\nsymlinks/\nagents/\n",
    )?;
    println!("  [created]   .agent-wiki/.gitignore");
    Ok(())
}

fn ensure_gitignore(repo_root: &Path) -> Result<()> {
    let path = repo_root.join(".gitignore");
    let entry = ".agent-wiki";
    if path.exists() {
        let content = fs::read_to_string(&path)?;
        if content.contains(entry) {
            return Ok(());
        }
        fs::write(&path, format!("{}\n\n# agent-wiki\n{entry}\n", content.trim_end()))?;
    } else {
        fs::write(&path, format!("# agent-wiki\n{entry}\n"))?;
    }
    println!("  [gitignore] .agent-wiki added to .gitignore");
    Ok(())
}

fn ensure_templates(wiki_root: &Path) -> Result<()> {
    let dir = wiki_root.join("templates");
    fs::create_dir_all(&dir)?;

    write_if_missing(
        &dir.join("AGENT.template.md"),
        include_str!("../../templates/AGENT.template.md"),
        "  [created]   .agent-wiki/templates/AGENT.template.md",
    )?;
    write_if_missing(
        &dir.join("instructions.md"),
        include_str!("../../templates/instructions.md"),
        "  [created]   .agent-wiki/templates/instructions.md  (edit to customize)",
    )?;
    write_if_missing(
        &dir.join("WIKI_UPDATE.md"),
        include_str!("../../templates/WIKI_UPDATE.md"),
        "  [created]   .agent-wiki/templates/WIKI_UPDATE.md",
    )?;
    write_if_missing(
        &dir.join("WIKI_MERGE.md"),
        include_str!("../../templates/WIKI_MERGE.md"),
        "  [created]   .agent-wiki/templates/WIKI_MERGE.md",
    )?;
    write_if_missing(
        &wiki_root.join("llm.md"),
        include_str!("../../templates/llm.md"),
        "  [created]   .agent-wiki/llm.md",
    )?;
    Ok(())
}

fn write_if_missing(path: &Path, content: &str, msg: &str) -> Result<()> {
    if path.exists() {
        return Ok(());
    }
    if let Some(dir) = path.parent() {
        fs::create_dir_all(dir)?;
    }
    fs::write(path, content)?;
    println!("{msg}");
    Ok(())
}
